PS_INFRA_NETWORK_ID: ps-local-infra_localinfra-network
PS_INFRA_MOUNT_SOURCE_PATH: /var/www/html
PS_INFRA_MOUNT_TARGET_PATH: /var/www
PS_TEMPLATES_IMAGES_PREFIX: ps-local-infra_template
PS_ENTRY_POINT_SCRIPT_URL: https://raw.githubusercontent.com/PrestaInfra/ps-auto-install-script/main/setup.sh